version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - 80:80
        restart: always
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        volumes_from:
            - php

    php:
        build: .
        restart: always
        volumes:
          - ./app/:/var/www/html/

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Bangkok

volumes:
    db_data: {}